### ISSUE TITLE
MAUI sample won't build

### ISSUE THREAD

**Issue by nathenxbrewer** [AvaloniaUI/AvaloniaMauiHybrid#25]
Trying to build the MAUI sample app. Also followed the how-to on a blank MAUI app and am getting the same error: 

1>Xamarin.Shared.Sdk.targets(1641,3): Error  : clang++ exited with code 1:
ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/nathenbrewer/.nuget/packages/harfbuzzsharp.nativeassets.ios/2.8.2.3/runtimes/ios/native/libHarfBuzzSharp.framework/libHarfBuzzSharp' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Trying to run on iOS Simulator

**Comment by maxkatz6** [comment]
I just tried to reproduce this issue, but without any success.
Just in case, I also adjusted MAUI related code to work with latest currently stable version.

Try clean obj/bin folders, update latest dependencies, sdk and workloads.
If you still have this issue, consider opening issue at https://github.com/xamarin/xamarin-macios. Since managed dependencies linking is implemented in that repository.
